name: intelligent-tests-pr
on:
  workflow_dispatch:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened, review_requested]

permissions:
  actions: read
  pull-requests: write
jobs:
  display_test_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build output

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build output
             ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace