name: intelligent-tests-pr
on:
  workflow_dispatch:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened, review_requested]

permissions:
  actions: read
  pull-requests: write
jobs:
  display_test_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "Hello, world!" > myfile.txt
          cat myfile.txt
      
      - name: output file
        id: output_file
        run: | 
          # make myfile.txt as action output
          {
            echo 'MESSAGE<<EOF'
            cat myfile.txt
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!--- CI Output -->

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build output
            <!--- CI Output -->
             ${{ steps.fc.outputs.comment-id }}
             ${{ steps.output_file.outputs.MESSAGE}}
          edit-mode: replace
